language: csharp  
sudo: required  
dist: xenial
addons:  
  apt:
    packages:
    - gettext
    - libcurl4-openssl-dev
    - libicu-dev
    - libssl-dev
    - libunwind8
    - zlib1g
mono:  
  - 4.2.3
os:  
  - linux
  #- osx # todo: wait for https://github.com/dotnet/corefx/issues/9394
dotnet: 1.0.0-preview2.1-003177
osx_image: xcode7.3  
branches:  
  only:
    - master
before_install:  
  - if test "$TRAVIS_OS_NAME" == "osx"; then brew update; brew install openssl; ln -s /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib /usr/local/lib/; ln -s /usr/local/opt/openssl/lib/libssl.1.0.0.dylib /usr/local/lib/; fiopenssl; fi
  - chmod +x ./Scripts/Linux/build.sh
  - chmod +x ./Scripts/Linux/runTests.sh
install:  
  - sh -c 'echo "deb [arch=amd64] https://apt-mo.trafficmanager.net/repos/dotnet-release/ xenial main" > /etc/apt/sources.list.d/dotnetdev.list'
  - apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 417A0893
  - apt-get update
  - apt-get install dotnet-dev-1.0.0-preview2.1-003177
script:  
  - ./Scripts/Linux/build.sh
  - ./Scripts/Linux/runTests.sh
