language: csharp
mono: none
dotnet: 2.1

services:
  - docker

os:
  - linux

branches:
  only:
    - master

script:
  - chmod +x ./Scripts/Linux/build.sh
  - chmod +x ./Scripts/Linux/runTests.sh
  - ./Scripts/Linux/build.sh
  - ./Scripts/Linux/runTests.sh
  - dotnet publish ./Src/Kronos.Server/ -c Release -o ./publish

after_success:
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
  - echo "TRAVIS_BRANCH=$TRAVIS_BRANCH, PR=$PR, BRANCH=$BRANCH"
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker build -t lukaszpyrzyk/kronos .
  - 'if [ "$BRANCH" == "master" ]; then
          echo "Pushing to the master!";
          docker push lukaszpyrzyk/kronos;
          echo "Pushing to the master is done";
     else
          echo "Changing branch tag";
          docker tag lukaszpyrzyk/kronos lukaszpyrzyk/kronos:$BRANCH;
          echo "Changing branch tag done";
          docker images --all;
          echo "Publishing" lukaszpyrzyk/kronos:$BRANCH;
          docker push lukaszpyrzyk/kronos:$BRANCH;
          echo "Pushing branch done";
     fi'
