// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Request.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from Request.proto</summary>
public static partial class RequestReflection {

  #region Descriptor
  /// <summary>File descriptor for Request.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static RequestReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "Cg1SZXF1ZXN0LnByb3RvGgxpbnNlcnQucHJvdG8aCWdldC5wcm90bxoMZGVs",
          "ZXRlLnByb3RvGgtjb3VudC5wcm90bxoOY29udGFpbnMucHJvdG8aC2NsZWFy",
          "LnByb3RvIscCCgdSZXF1ZXN0EiUKDUluc2VydFJlcXVlc3QYASABKAsyDi5J",
          "bnNlcnRSZXF1ZXN0Eh8KCkdldFJlcXVlc3QYAiABKAsyCy5HZXRSZXF1ZXN0",
          "EiUKDURlbGV0ZVJlcXVlc3QYAyABKAsyDi5EZWxldGVSZXF1ZXN0EikKD0Nv",
          "bnRhaW5zUmVxdWVzdBgEIAEoCzIQLkNvbnRhaW5zUmVxdWVzdBIjCgxDb3Vu",
          "dFJlcXVlc3QYBSABKAsyDS5Db3VudFJlcXVlc3QSIwoMQ2xlYXJSZXF1ZXN0",
          "GAYgASgLMg0uQ2xlYXJSZXF1ZXN0IlgKBFR5cGUSCwoHVW5rbm93bhAAEgoK",
          "Bkluc2VydBABEgcKA0dldBACEgoKBkRlbGV0ZRADEgkKBUNvdW50EAQSDAoI",
          "Q29udGFpbnMQBRIJCgVDbGVhchAGYgZwcm90bzM="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { global::InsertReflection.Descriptor, global::GetReflection.Descriptor, global::DeleteReflection.Descriptor, global::CountReflection.Descriptor, global::ContainsReflection.Descriptor, global::ClearReflection.Descriptor, },
        new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::Request), global::Request.Parser, new[]{ "InsertRequest", "GetRequest", "DeleteRequest", "ContainsRequest", "CountRequest", "ClearRequest" }, null, new[]{ typeof(global::Request.Types.Type) }, null)
        }));
  }
  #endregion

}
#region Messages
public sealed partial class Request : pb::IMessage<Request> {
  private static readonly pb::MessageParser<Request> _parser = new pb::MessageParser<Request>(() => new Request());
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<Request> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::RequestReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public Request() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public Request(Request other) : this() {
    InsertRequest = other.insertRequest_ != null ? other.InsertRequest.Clone() : null;
    GetRequest = other.getRequest_ != null ? other.GetRequest.Clone() : null;
    DeleteRequest = other.deleteRequest_ != null ? other.DeleteRequest.Clone() : null;
    ContainsRequest = other.containsRequest_ != null ? other.ContainsRequest.Clone() : null;
    CountRequest = other.countRequest_ != null ? other.CountRequest.Clone() : null;
    ClearRequest = other.clearRequest_ != null ? other.ClearRequest.Clone() : null;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public Request Clone() {
    return new Request(this);
  }

  /// <summary>Field number for the "InsertRequest" field.</summary>
  public const int InsertRequestFieldNumber = 1;
  private global::InsertRequest insertRequest_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::InsertRequest InsertRequest {
    get { return insertRequest_; }
    set {
      insertRequest_ = value;
    }
  }

  /// <summary>Field number for the "GetRequest" field.</summary>
  public const int GetRequestFieldNumber = 2;
  private global::GetRequest getRequest_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::GetRequest GetRequest {
    get { return getRequest_; }
    set {
      getRequest_ = value;
    }
  }

  /// <summary>Field number for the "DeleteRequest" field.</summary>
  public const int DeleteRequestFieldNumber = 3;
  private global::DeleteRequest deleteRequest_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::DeleteRequest DeleteRequest {
    get { return deleteRequest_; }
    set {
      deleteRequest_ = value;
    }
  }

  /// <summary>Field number for the "ContainsRequest" field.</summary>
  public const int ContainsRequestFieldNumber = 4;
  private global::ContainsRequest containsRequest_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::ContainsRequest ContainsRequest {
    get { return containsRequest_; }
    set {
      containsRequest_ = value;
    }
  }

  /// <summary>Field number for the "CountRequest" field.</summary>
  public const int CountRequestFieldNumber = 5;
  private global::CountRequest countRequest_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::CountRequest CountRequest {
    get { return countRequest_; }
    set {
      countRequest_ = value;
    }
  }

  /// <summary>Field number for the "ClearRequest" field.</summary>
  public const int ClearRequestFieldNumber = 6;
  private global::ClearRequest clearRequest_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::ClearRequest ClearRequest {
    get { return clearRequest_; }
    set {
      clearRequest_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as Request);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(Request other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (!object.Equals(InsertRequest, other.InsertRequest)) return false;
    if (!object.Equals(GetRequest, other.GetRequest)) return false;
    if (!object.Equals(DeleteRequest, other.DeleteRequest)) return false;
    if (!object.Equals(ContainsRequest, other.ContainsRequest)) return false;
    if (!object.Equals(CountRequest, other.CountRequest)) return false;
    if (!object.Equals(ClearRequest, other.ClearRequest)) return false;
    return true;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (insertRequest_ != null) hash ^= InsertRequest.GetHashCode();
    if (getRequest_ != null) hash ^= GetRequest.GetHashCode();
    if (deleteRequest_ != null) hash ^= DeleteRequest.GetHashCode();
    if (containsRequest_ != null) hash ^= ContainsRequest.GetHashCode();
    if (countRequest_ != null) hash ^= CountRequest.GetHashCode();
    if (clearRequest_ != null) hash ^= ClearRequest.GetHashCode();
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (insertRequest_ != null) {
      output.WriteRawTag(10);
      output.WriteMessage(InsertRequest);
    }
    if (getRequest_ != null) {
      output.WriteRawTag(18);
      output.WriteMessage(GetRequest);
    }
    if (deleteRequest_ != null) {
      output.WriteRawTag(26);
      output.WriteMessage(DeleteRequest);
    }
    if (containsRequest_ != null) {
      output.WriteRawTag(34);
      output.WriteMessage(ContainsRequest);
    }
    if (countRequest_ != null) {
      output.WriteRawTag(42);
      output.WriteMessage(CountRequest);
    }
    if (clearRequest_ != null) {
      output.WriteRawTag(50);
      output.WriteMessage(ClearRequest);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (insertRequest_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(InsertRequest);
    }
    if (getRequest_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(GetRequest);
    }
    if (deleteRequest_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(DeleteRequest);
    }
    if (containsRequest_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(ContainsRequest);
    }
    if (countRequest_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(CountRequest);
    }
    if (clearRequest_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(ClearRequest);
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(Request other) {
    if (other == null) {
      return;
    }
    if (other.insertRequest_ != null) {
      if (insertRequest_ == null) {
        insertRequest_ = new global::InsertRequest();
      }
      InsertRequest.MergeFrom(other.InsertRequest);
    }
    if (other.getRequest_ != null) {
      if (getRequest_ == null) {
        getRequest_ = new global::GetRequest();
      }
      GetRequest.MergeFrom(other.GetRequest);
    }
    if (other.deleteRequest_ != null) {
      if (deleteRequest_ == null) {
        deleteRequest_ = new global::DeleteRequest();
      }
      DeleteRequest.MergeFrom(other.DeleteRequest);
    }
    if (other.containsRequest_ != null) {
      if (containsRequest_ == null) {
        containsRequest_ = new global::ContainsRequest();
      }
      ContainsRequest.MergeFrom(other.ContainsRequest);
    }
    if (other.countRequest_ != null) {
      if (countRequest_ == null) {
        countRequest_ = new global::CountRequest();
      }
      CountRequest.MergeFrom(other.CountRequest);
    }
    if (other.clearRequest_ != null) {
      if (clearRequest_ == null) {
        clearRequest_ = new global::ClearRequest();
      }
      ClearRequest.MergeFrom(other.ClearRequest);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          input.SkipLastField();
          break;
        case 10: {
          if (insertRequest_ == null) {
            insertRequest_ = new global::InsertRequest();
          }
          input.ReadMessage(insertRequest_);
          break;
        }
        case 18: {
          if (getRequest_ == null) {
            getRequest_ = new global::GetRequest();
          }
          input.ReadMessage(getRequest_);
          break;
        }
        case 26: {
          if (deleteRequest_ == null) {
            deleteRequest_ = new global::DeleteRequest();
          }
          input.ReadMessage(deleteRequest_);
          break;
        }
        case 34: {
          if (containsRequest_ == null) {
            containsRequest_ = new global::ContainsRequest();
          }
          input.ReadMessage(containsRequest_);
          break;
        }
        case 42: {
          if (countRequest_ == null) {
            countRequest_ = new global::CountRequest();
          }
          input.ReadMessage(countRequest_);
          break;
        }
        case 50: {
          if (clearRequest_ == null) {
            clearRequest_ = new global::ClearRequest();
          }
          input.ReadMessage(clearRequest_);
          break;
        }
      }
    }
  }

  #region Nested types
  /// <summary>Container for nested types declared in the Request message type.</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static partial class Types {
    public enum Type {
      [pbr::OriginalName("Unknown")] Unknown = 0,
      [pbr::OriginalName("Insert")] Insert = 1,
      [pbr::OriginalName("Get")] Get = 2,
      [pbr::OriginalName("Delete")] Delete = 3,
      [pbr::OriginalName("Count")] Count = 4,
      [pbr::OriginalName("Contains")] Contains = 5,
      [pbr::OriginalName("Clear")] Clear = 6,
    }

  }
  #endregion

}

#endregion


#endregion Designer generated code
