// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RequestType.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from RequestType.proto</summary>
public static partial class RequestTypeReflection {

  #region Descriptor
  /// <summary>File descriptor for RequestType.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static RequestTypeReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChFSZXF1ZXN0VHlwZS5wcm90bypfCgtSZXF1ZXN0VHlwZRILCgdVbmtub3du",
          "EAASCgoGSW5zZXJ0EAESBwoDR2V0EAISCgoGRGVsZXRlEAMSCQoFQ291bnQQ",
          "BBIMCghDb250YWlucxAFEgkKBUNsZWFyEAZiBnByb3RvMw=="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(new[] {typeof(global::RequestType), }, null));
  }
  #endregion

}
#region Enums
public enum RequestType {
  [pbr::OriginalName("Unknown")] Unknown = 0,
  [pbr::OriginalName("Insert")] Insert = 1,
  [pbr::OriginalName("Get")] Get = 2,
  [pbr::OriginalName("Delete")] Delete = 3,
  [pbr::OriginalName("Count")] Count = 4,
  [pbr::OriginalName("Contains")] Contains = 5,
  [pbr::OriginalName("Clear")] Clear = 6,
}

#endregion


#endregion Designer generated code
