// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: request.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Kronos.Core.Messages {

  /// <summary>Holder for reflection information generated from request.proto</summary>
  public static partial class RequestReflection {

    #region Descriptor
    /// <summary>File descriptor for request.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static RequestReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg1yZXF1ZXN0LnByb3RvGgphdXRoLnByb3RvGhFyZXF1ZXN0VHlwZS5wcm90",
            "bxoMaW5zZXJ0LnByb3RvGglnZXQucHJvdG8aDGRlbGV0ZS5wcm90bxoLY291",
            "bnQucHJvdG8aDmNvbnRhaW5zLnByb3RvGgtjbGVhci5wcm90bxoLc3RhdHMu",
            "cHJvdG8iwwIKB1JlcXVlc3QSEwoEQXV0aBgBIAEoCzIFLkF1dGgSGgoEVHlw",
            "ZRgCIAEoDjIMLlJlcXVlc3RUeXBlEiUKDUluc2VydFJlcXVlc3QYAyABKAsy",
            "Di5JbnNlcnRSZXF1ZXN0Eh8KCkdldFJlcXVlc3QYBCABKAsyCy5HZXRSZXF1",
            "ZXN0EiUKDURlbGV0ZVJlcXVlc3QYBSABKAsyDi5EZWxldGVSZXF1ZXN0EikK",
            "D0NvbnRhaW5zUmVxdWVzdBgGIAEoCzIQLkNvbnRhaW5zUmVxdWVzdBIjCgxD",
            "b3VudFJlcXVlc3QYByABKAsyDS5Db3VudFJlcXVlc3QSIwoMQ2xlYXJSZXF1",
            "ZXN0GAggASgLMg0uQ2xlYXJSZXF1ZXN0EiMKDFN0YXRzUmVxdWVzdBgJIAEo",
            "CzINLlN0YXRzUmVxdWVzdEIXqgIUS3Jvbm9zLkNvcmUuTWVzc2FnZXNiBnBy",
            "b3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Kronos.Core.Messages.AuthReflection.Descriptor, global::Kronos.Core.Messages.RequestTypeReflection.Descriptor, global::Kronos.Core.Messages.InsertReflection.Descriptor, global::Kronos.Core.Messages.GetReflection.Descriptor, global::Kronos.Core.Messages.DeleteReflection.Descriptor, global::Kronos.Core.Messages.CountReflection.Descriptor, global::Kronos.Core.Messages.ContainsReflection.Descriptor, global::Kronos.Core.Messages.ClearReflection.Descriptor, global::Kronos.Core.Messages.StatsReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Kronos.Core.Messages.Request), global::Kronos.Core.Messages.Request.Parser, new[]{ "Auth", "Type", "InsertRequest", "GetRequest", "DeleteRequest", "ContainsRequest", "CountRequest", "ClearRequest", "StatsRequest" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class Request : pb::IMessage<Request> {
    private static readonly pb::MessageParser<Request> _parser = new pb::MessageParser<Request>(() => new Request());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Request> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Kronos.Core.Messages.RequestReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Request() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Request(Request other) : this() {
      auth_ = other.auth_ != null ? other.auth_.Clone() : null;
      type_ = other.type_;
      insertRequest_ = other.insertRequest_ != null ? other.insertRequest_.Clone() : null;
      getRequest_ = other.getRequest_ != null ? other.getRequest_.Clone() : null;
      deleteRequest_ = other.deleteRequest_ != null ? other.deleteRequest_.Clone() : null;
      containsRequest_ = other.containsRequest_ != null ? other.containsRequest_.Clone() : null;
      countRequest_ = other.countRequest_ != null ? other.countRequest_.Clone() : null;
      clearRequest_ = other.clearRequest_ != null ? other.clearRequest_.Clone() : null;
      statsRequest_ = other.statsRequest_ != null ? other.statsRequest_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Request Clone() {
      return new Request(this);
    }

    /// <summary>Field number for the "Auth" field.</summary>
    public const int AuthFieldNumber = 1;
    private global::Kronos.Core.Messages.Auth auth_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Kronos.Core.Messages.Auth Auth {
      get { return auth_; }
      set {
        auth_ = value;
      }
    }

    /// <summary>Field number for the "Type" field.</summary>
    public const int TypeFieldNumber = 2;
    private global::Kronos.Core.Messages.RequestType type_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Kronos.Core.Messages.RequestType Type {
      get { return type_; }
      set {
        type_ = value;
      }
    }

    /// <summary>Field number for the "InsertRequest" field.</summary>
    public const int InsertRequestFieldNumber = 3;
    private global::Kronos.Core.Messages.InsertRequest insertRequest_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Kronos.Core.Messages.InsertRequest InsertRequest {
      get { return insertRequest_; }
      set {
        insertRequest_ = value;
      }
    }

    /// <summary>Field number for the "GetRequest" field.</summary>
    public const int GetRequestFieldNumber = 4;
    private global::Kronos.Core.Messages.GetRequest getRequest_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Kronos.Core.Messages.GetRequest GetRequest {
      get { return getRequest_; }
      set {
        getRequest_ = value;
      }
    }

    /// <summary>Field number for the "DeleteRequest" field.</summary>
    public const int DeleteRequestFieldNumber = 5;
    private global::Kronos.Core.Messages.DeleteRequest deleteRequest_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Kronos.Core.Messages.DeleteRequest DeleteRequest {
      get { return deleteRequest_; }
      set {
        deleteRequest_ = value;
      }
    }

    /// <summary>Field number for the "ContainsRequest" field.</summary>
    public const int ContainsRequestFieldNumber = 6;
    private global::Kronos.Core.Messages.ContainsRequest containsRequest_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Kronos.Core.Messages.ContainsRequest ContainsRequest {
      get { return containsRequest_; }
      set {
        containsRequest_ = value;
      }
    }

    /// <summary>Field number for the "CountRequest" field.</summary>
    public const int CountRequestFieldNumber = 7;
    private global::Kronos.Core.Messages.CountRequest countRequest_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Kronos.Core.Messages.CountRequest CountRequest {
      get { return countRequest_; }
      set {
        countRequest_ = value;
      }
    }

    /// <summary>Field number for the "ClearRequest" field.</summary>
    public const int ClearRequestFieldNumber = 8;
    private global::Kronos.Core.Messages.ClearRequest clearRequest_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Kronos.Core.Messages.ClearRequest ClearRequest {
      get { return clearRequest_; }
      set {
        clearRequest_ = value;
      }
    }

    /// <summary>Field number for the "StatsRequest" field.</summary>
    public const int StatsRequestFieldNumber = 9;
    private global::Kronos.Core.Messages.StatsRequest statsRequest_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Kronos.Core.Messages.StatsRequest StatsRequest {
      get { return statsRequest_; }
      set {
        statsRequest_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Request);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Request other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Auth, other.Auth)) return false;
      if (Type != other.Type) return false;
      if (!object.Equals(InsertRequest, other.InsertRequest)) return false;
      if (!object.Equals(GetRequest, other.GetRequest)) return false;
      if (!object.Equals(DeleteRequest, other.DeleteRequest)) return false;
      if (!object.Equals(ContainsRequest, other.ContainsRequest)) return false;
      if (!object.Equals(CountRequest, other.CountRequest)) return false;
      if (!object.Equals(ClearRequest, other.ClearRequest)) return false;
      if (!object.Equals(StatsRequest, other.StatsRequest)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (auth_ != null) hash ^= Auth.GetHashCode();
      if (Type != 0) hash ^= Type.GetHashCode();
      if (insertRequest_ != null) hash ^= InsertRequest.GetHashCode();
      if (getRequest_ != null) hash ^= GetRequest.GetHashCode();
      if (deleteRequest_ != null) hash ^= DeleteRequest.GetHashCode();
      if (containsRequest_ != null) hash ^= ContainsRequest.GetHashCode();
      if (countRequest_ != null) hash ^= CountRequest.GetHashCode();
      if (clearRequest_ != null) hash ^= ClearRequest.GetHashCode();
      if (statsRequest_ != null) hash ^= StatsRequest.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (auth_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Auth);
      }
      if (Type != 0) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Type);
      }
      if (insertRequest_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(InsertRequest);
      }
      if (getRequest_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(GetRequest);
      }
      if (deleteRequest_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(DeleteRequest);
      }
      if (containsRequest_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(ContainsRequest);
      }
      if (countRequest_ != null) {
        output.WriteRawTag(58);
        output.WriteMessage(CountRequest);
      }
      if (clearRequest_ != null) {
        output.WriteRawTag(66);
        output.WriteMessage(ClearRequest);
      }
      if (statsRequest_ != null) {
        output.WriteRawTag(74);
        output.WriteMessage(StatsRequest);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (auth_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Auth);
      }
      if (Type != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
      }
      if (insertRequest_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(InsertRequest);
      }
      if (getRequest_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(GetRequest);
      }
      if (deleteRequest_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(DeleteRequest);
      }
      if (containsRequest_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ContainsRequest);
      }
      if (countRequest_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(CountRequest);
      }
      if (clearRequest_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ClearRequest);
      }
      if (statsRequest_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(StatsRequest);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Request other) {
      if (other == null) {
        return;
      }
      if (other.auth_ != null) {
        if (auth_ == null) {
          auth_ = new global::Kronos.Core.Messages.Auth();
        }
        Auth.MergeFrom(other.Auth);
      }
      if (other.Type != 0) {
        Type = other.Type;
      }
      if (other.insertRequest_ != null) {
        if (insertRequest_ == null) {
          insertRequest_ = new global::Kronos.Core.Messages.InsertRequest();
        }
        InsertRequest.MergeFrom(other.InsertRequest);
      }
      if (other.getRequest_ != null) {
        if (getRequest_ == null) {
          getRequest_ = new global::Kronos.Core.Messages.GetRequest();
        }
        GetRequest.MergeFrom(other.GetRequest);
      }
      if (other.deleteRequest_ != null) {
        if (deleteRequest_ == null) {
          deleteRequest_ = new global::Kronos.Core.Messages.DeleteRequest();
        }
        DeleteRequest.MergeFrom(other.DeleteRequest);
      }
      if (other.containsRequest_ != null) {
        if (containsRequest_ == null) {
          containsRequest_ = new global::Kronos.Core.Messages.ContainsRequest();
        }
        ContainsRequest.MergeFrom(other.ContainsRequest);
      }
      if (other.countRequest_ != null) {
        if (countRequest_ == null) {
          countRequest_ = new global::Kronos.Core.Messages.CountRequest();
        }
        CountRequest.MergeFrom(other.CountRequest);
      }
      if (other.clearRequest_ != null) {
        if (clearRequest_ == null) {
          clearRequest_ = new global::Kronos.Core.Messages.ClearRequest();
        }
        ClearRequest.MergeFrom(other.ClearRequest);
      }
      if (other.statsRequest_ != null) {
        if (statsRequest_ == null) {
          statsRequest_ = new global::Kronos.Core.Messages.StatsRequest();
        }
        StatsRequest.MergeFrom(other.StatsRequest);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (auth_ == null) {
              auth_ = new global::Kronos.Core.Messages.Auth();
            }
            input.ReadMessage(auth_);
            break;
          }
          case 16: {
            type_ = (global::Kronos.Core.Messages.RequestType) input.ReadEnum();
            break;
          }
          case 26: {
            if (insertRequest_ == null) {
              insertRequest_ = new global::Kronos.Core.Messages.InsertRequest();
            }
            input.ReadMessage(insertRequest_);
            break;
          }
          case 34: {
            if (getRequest_ == null) {
              getRequest_ = new global::Kronos.Core.Messages.GetRequest();
            }
            input.ReadMessage(getRequest_);
            break;
          }
          case 42: {
            if (deleteRequest_ == null) {
              deleteRequest_ = new global::Kronos.Core.Messages.DeleteRequest();
            }
            input.ReadMessage(deleteRequest_);
            break;
          }
          case 50: {
            if (containsRequest_ == null) {
              containsRequest_ = new global::Kronos.Core.Messages.ContainsRequest();
            }
            input.ReadMessage(containsRequest_);
            break;
          }
          case 58: {
            if (countRequest_ == null) {
              countRequest_ = new global::Kronos.Core.Messages.CountRequest();
            }
            input.ReadMessage(countRequest_);
            break;
          }
          case 66: {
            if (clearRequest_ == null) {
              clearRequest_ = new global::Kronos.Core.Messages.ClearRequest();
            }
            input.ReadMessage(clearRequest_);
            break;
          }
          case 74: {
            if (statsRequest_ == null) {
              statsRequest_ = new global::Kronos.Core.Messages.StatsRequest();
            }
            input.ReadMessage(statsRequest_);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
