// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: response.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Kronos.Core.Messages {

  /// <summary>Holder for reflection information generated from response.proto</summary>
  public static partial class ResponseReflection {

    #region Descriptor
    /// <summary>File descriptor for response.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ResponseReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg5yZXNwb25zZS5wcm90bxoMaW5zZXJ0LnByb3RvGglnZXQucHJvdG8aDGRl",
            "bGV0ZS5wcm90bxoLY291bnQucHJvdG8aDmNvbnRhaW5zLnByb3RvGgtjbGVh",
            "ci5wcm90bxoLc3RhdHMucHJvdG8iswIKCFJlc3BvbnNlEhEKCUV4Y2VwdGlv",
            "bhgBIAEoCRInCg5JbnNlcnRSZXNwb25zZRgCIAEoCzIPLkluc2VydFJlc3Bv",
            "bnNlEiAKCkdldFJlc3BvbmUYAyABKAsyDC5HZXRSZXNwb25zZRInCg5EZWxl",
            "dGVSZXNwb25zZRgEIAEoCzIPLkRlbGV0ZVJlc3BvbnNlEisKEENvbnRhaW5z",
            "UmVzcG9uc2UYBSABKAsyES5Db250YWluc1Jlc3BvbnNlEiUKDUNvdW50UmVz",
            "cG9uc2UYBiABKAsyDi5Db3VudFJlc3BvbnNlEiUKDUNsZWFyUmVzcG9uc2UY",
            "ByABKAsyDi5DbGVhclJlc3BvbnNlEiUKDVN0YXRzUmVzcG9uc2UYCCABKAsy",
            "Di5TdGF0c1Jlc3BvbnNlQheqAhRLcm9ub3MuQ29yZS5NZXNzYWdlc2IGcHJv",
            "dG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Kronos.Core.Messages.InsertReflection.Descriptor, global::Kronos.Core.Messages.GetReflection.Descriptor, global::Kronos.Core.Messages.DeleteReflection.Descriptor, global::Kronos.Core.Messages.CountReflection.Descriptor, global::Kronos.Core.Messages.ContainsReflection.Descriptor, global::Kronos.Core.Messages.ClearReflection.Descriptor, global::Kronos.Core.Messages.StatsReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Kronos.Core.Messages.Response), global::Kronos.Core.Messages.Response.Parser, new[]{ "Exception", "InsertResponse", "GetRespone", "DeleteResponse", "ContainsResponse", "CountResponse", "ClearResponse", "StatsResponse" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class Response : pb::IMessage<Response> {
    private static readonly pb::MessageParser<Response> _parser = new pb::MessageParser<Response>(() => new Response());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Response> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Kronos.Core.Messages.ResponseReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Response() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Response(Response other) : this() {
      exception_ = other.exception_;
      insertResponse_ = other.insertResponse_ != null ? other.insertResponse_.Clone() : null;
      getRespone_ = other.getRespone_ != null ? other.getRespone_.Clone() : null;
      deleteResponse_ = other.deleteResponse_ != null ? other.deleteResponse_.Clone() : null;
      containsResponse_ = other.containsResponse_ != null ? other.containsResponse_.Clone() : null;
      countResponse_ = other.countResponse_ != null ? other.countResponse_.Clone() : null;
      clearResponse_ = other.clearResponse_ != null ? other.clearResponse_.Clone() : null;
      statsResponse_ = other.statsResponse_ != null ? other.statsResponse_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Response Clone() {
      return new Response(this);
    }

    /// <summary>Field number for the "Exception" field.</summary>
    public const int ExceptionFieldNumber = 1;
    private string exception_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Exception {
      get { return exception_; }
      set {
        exception_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "InsertResponse" field.</summary>
    public const int InsertResponseFieldNumber = 2;
    private global::Kronos.Core.Messages.InsertResponse insertResponse_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Kronos.Core.Messages.InsertResponse InsertResponse {
      get { return insertResponse_; }
      set {
        insertResponse_ = value;
      }
    }

    /// <summary>Field number for the "GetRespone" field.</summary>
    public const int GetResponeFieldNumber = 3;
    private global::Kronos.Core.Messages.GetResponse getRespone_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Kronos.Core.Messages.GetResponse GetRespone {
      get { return getRespone_; }
      set {
        getRespone_ = value;
      }
    }

    /// <summary>Field number for the "DeleteResponse" field.</summary>
    public const int DeleteResponseFieldNumber = 4;
    private global::Kronos.Core.Messages.DeleteResponse deleteResponse_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Kronos.Core.Messages.DeleteResponse DeleteResponse {
      get { return deleteResponse_; }
      set {
        deleteResponse_ = value;
      }
    }

    /// <summary>Field number for the "ContainsResponse" field.</summary>
    public const int ContainsResponseFieldNumber = 5;
    private global::Kronos.Core.Messages.ContainsResponse containsResponse_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Kronos.Core.Messages.ContainsResponse ContainsResponse {
      get { return containsResponse_; }
      set {
        containsResponse_ = value;
      }
    }

    /// <summary>Field number for the "CountResponse" field.</summary>
    public const int CountResponseFieldNumber = 6;
    private global::Kronos.Core.Messages.CountResponse countResponse_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Kronos.Core.Messages.CountResponse CountResponse {
      get { return countResponse_; }
      set {
        countResponse_ = value;
      }
    }

    /// <summary>Field number for the "ClearResponse" field.</summary>
    public const int ClearResponseFieldNumber = 7;
    private global::Kronos.Core.Messages.ClearResponse clearResponse_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Kronos.Core.Messages.ClearResponse ClearResponse {
      get { return clearResponse_; }
      set {
        clearResponse_ = value;
      }
    }

    /// <summary>Field number for the "StatsResponse" field.</summary>
    public const int StatsResponseFieldNumber = 8;
    private global::Kronos.Core.Messages.StatsResponse statsResponse_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Kronos.Core.Messages.StatsResponse StatsResponse {
      get { return statsResponse_; }
      set {
        statsResponse_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Response);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Response other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Exception != other.Exception) return false;
      if (!object.Equals(InsertResponse, other.InsertResponse)) return false;
      if (!object.Equals(GetRespone, other.GetRespone)) return false;
      if (!object.Equals(DeleteResponse, other.DeleteResponse)) return false;
      if (!object.Equals(ContainsResponse, other.ContainsResponse)) return false;
      if (!object.Equals(CountResponse, other.CountResponse)) return false;
      if (!object.Equals(ClearResponse, other.ClearResponse)) return false;
      if (!object.Equals(StatsResponse, other.StatsResponse)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Exception.Length != 0) hash ^= Exception.GetHashCode();
      if (insertResponse_ != null) hash ^= InsertResponse.GetHashCode();
      if (getRespone_ != null) hash ^= GetRespone.GetHashCode();
      if (deleteResponse_ != null) hash ^= DeleteResponse.GetHashCode();
      if (containsResponse_ != null) hash ^= ContainsResponse.GetHashCode();
      if (countResponse_ != null) hash ^= CountResponse.GetHashCode();
      if (clearResponse_ != null) hash ^= ClearResponse.GetHashCode();
      if (statsResponse_ != null) hash ^= StatsResponse.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Exception.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Exception);
      }
      if (insertResponse_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(InsertResponse);
      }
      if (getRespone_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(GetRespone);
      }
      if (deleteResponse_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(DeleteResponse);
      }
      if (containsResponse_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(ContainsResponse);
      }
      if (countResponse_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(CountResponse);
      }
      if (clearResponse_ != null) {
        output.WriteRawTag(58);
        output.WriteMessage(ClearResponse);
      }
      if (statsResponse_ != null) {
        output.WriteRawTag(66);
        output.WriteMessage(StatsResponse);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Exception.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Exception);
      }
      if (insertResponse_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(InsertResponse);
      }
      if (getRespone_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(GetRespone);
      }
      if (deleteResponse_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(DeleteResponse);
      }
      if (containsResponse_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ContainsResponse);
      }
      if (countResponse_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(CountResponse);
      }
      if (clearResponse_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ClearResponse);
      }
      if (statsResponse_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(StatsResponse);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Response other) {
      if (other == null) {
        return;
      }
      if (other.Exception.Length != 0) {
        Exception = other.Exception;
      }
      if (other.insertResponse_ != null) {
        if (insertResponse_ == null) {
          insertResponse_ = new global::Kronos.Core.Messages.InsertResponse();
        }
        InsertResponse.MergeFrom(other.InsertResponse);
      }
      if (other.getRespone_ != null) {
        if (getRespone_ == null) {
          getRespone_ = new global::Kronos.Core.Messages.GetResponse();
        }
        GetRespone.MergeFrom(other.GetRespone);
      }
      if (other.deleteResponse_ != null) {
        if (deleteResponse_ == null) {
          deleteResponse_ = new global::Kronos.Core.Messages.DeleteResponse();
        }
        DeleteResponse.MergeFrom(other.DeleteResponse);
      }
      if (other.containsResponse_ != null) {
        if (containsResponse_ == null) {
          containsResponse_ = new global::Kronos.Core.Messages.ContainsResponse();
        }
        ContainsResponse.MergeFrom(other.ContainsResponse);
      }
      if (other.countResponse_ != null) {
        if (countResponse_ == null) {
          countResponse_ = new global::Kronos.Core.Messages.CountResponse();
        }
        CountResponse.MergeFrom(other.CountResponse);
      }
      if (other.clearResponse_ != null) {
        if (clearResponse_ == null) {
          clearResponse_ = new global::Kronos.Core.Messages.ClearResponse();
        }
        ClearResponse.MergeFrom(other.ClearResponse);
      }
      if (other.statsResponse_ != null) {
        if (statsResponse_ == null) {
          statsResponse_ = new global::Kronos.Core.Messages.StatsResponse();
        }
        StatsResponse.MergeFrom(other.StatsResponse);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Exception = input.ReadString();
            break;
          }
          case 18: {
            if (insertResponse_ == null) {
              insertResponse_ = new global::Kronos.Core.Messages.InsertResponse();
            }
            input.ReadMessage(insertResponse_);
            break;
          }
          case 26: {
            if (getRespone_ == null) {
              getRespone_ = new global::Kronos.Core.Messages.GetResponse();
            }
            input.ReadMessage(getRespone_);
            break;
          }
          case 34: {
            if (deleteResponse_ == null) {
              deleteResponse_ = new global::Kronos.Core.Messages.DeleteResponse();
            }
            input.ReadMessage(deleteResponse_);
            break;
          }
          case 42: {
            if (containsResponse_ == null) {
              containsResponse_ = new global::Kronos.Core.Messages.ContainsResponse();
            }
            input.ReadMessage(containsResponse_);
            break;
          }
          case 50: {
            if (countResponse_ == null) {
              countResponse_ = new global::Kronos.Core.Messages.CountResponse();
            }
            input.ReadMessage(countResponse_);
            break;
          }
          case 58: {
            if (clearResponse_ == null) {
              clearResponse_ = new global::Kronos.Core.Messages.ClearResponse();
            }
            input.ReadMessage(clearResponse_);
            break;
          }
          case 66: {
            if (statsResponse_ == null) {
              statsResponse_ = new global::Kronos.Core.Messages.StatsResponse();
            }
            input.ReadMessage(statsResponse_);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
