// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Response.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Kronos.Core.Messages {

  /// <summary>Holder for reflection information generated from Response.proto</summary>
  public static partial class ResponseReflection {

    #region Descriptor
    /// <summary>File descriptor for Response.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ResponseReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg5SZXNwb25zZS5wcm90bxoRcmVxdWVzdFR5cGUucHJvdG8aDGluc2VydC5w",
            "cm90bxoJZ2V0LnByb3RvGgxkZWxldGUucHJvdG8aC2NvdW50LnByb3RvGg5j",
            "b250YWlucy5wcm90bxoLY2xlYXIucHJvdG8ilQIKCFJlc3BvbnNlEhoKBFR5",
            "cGUYASABKA4yDC5SZXF1ZXN0VHlwZRInCg5JbnNlcnRSZXNwb25zZRgCIAEo",
            "CzIPLkluc2VydFJlc3BvbnNlEiAKCkdldFJlc3BvbmUYAyABKAsyDC5HZXRS",
            "ZXNwb25zZRInCg5EZWxldGVSZXNwb25zZRgEIAEoCzIPLkRlbGV0ZVJlc3Bv",
            "bnNlEisKEENvbnRhaW5zUmVzcG9uc2UYBSABKAsyES5Db250YWluc1Jlc3Bv",
            "bnNlEiUKDUNvdW50UmVzcG9uc2UYBiABKAsyDi5Db3VudFJlc3BvbnNlEiUK",
            "DUNsZWFyUmVzcG9uc2UYByABKAsyDi5DbGVhclJlc3BvbnNlQheqAhRLcm9u",
            "b3MuQ29yZS5NZXNzYWdlc2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Kronos.Core.Messages.RequestTypeReflection.Descriptor, global::Kronos.Core.Messages.InsertReflection.Descriptor, global::Kronos.Core.Messages.GetReflection.Descriptor, global::Kronos.Core.Messages.DeleteReflection.Descriptor, global::Kronos.Core.Messages.CountReflection.Descriptor, global::Kronos.Core.Messages.ContainsReflection.Descriptor, global::Kronos.Core.Messages.ClearReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Kronos.Core.Messages.Response), global::Kronos.Core.Messages.Response.Parser, new[]{ "Type", "InsertResponse", "GetRespone", "DeleteResponse", "ContainsResponse", "CountResponse", "ClearResponse" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class Response : pb::IMessage<Response> {
    private static readonly pb::MessageParser<Response> _parser = new pb::MessageParser<Response>(() => new Response());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Response> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Kronos.Core.Messages.ResponseReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Response() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Response(Response other) : this() {
      type_ = other.type_;
      InsertResponse = other.insertResponse_ != null ? other.InsertResponse.Clone() : null;
      GetRespone = other.getRespone_ != null ? other.GetRespone.Clone() : null;
      DeleteResponse = other.deleteResponse_ != null ? other.DeleteResponse.Clone() : null;
      ContainsResponse = other.containsResponse_ != null ? other.ContainsResponse.Clone() : null;
      CountResponse = other.countResponse_ != null ? other.CountResponse.Clone() : null;
      ClearResponse = other.clearResponse_ != null ? other.ClearResponse.Clone() : null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Response Clone() {
      return new Response(this);
    }

    /// <summary>Field number for the "Type" field.</summary>
    public const int TypeFieldNumber = 1;
    private global::Kronos.Core.Messages.RequestType type_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Kronos.Core.Messages.RequestType Type {
      get { return type_; }
      set {
        type_ = value;
      }
    }

    /// <summary>Field number for the "InsertResponse" field.</summary>
    public const int InsertResponseFieldNumber = 2;
    private global::Kronos.Core.Messages.InsertResponse insertResponse_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Kronos.Core.Messages.InsertResponse InsertResponse {
      get { return insertResponse_; }
      set {
        insertResponse_ = value;
      }
    }

    /// <summary>Field number for the "GetRespone" field.</summary>
    public const int GetResponeFieldNumber = 3;
    private global::Kronos.Core.Messages.GetResponse getRespone_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Kronos.Core.Messages.GetResponse GetRespone {
      get { return getRespone_; }
      set {
        getRespone_ = value;
      }
    }

    /// <summary>Field number for the "DeleteResponse" field.</summary>
    public const int DeleteResponseFieldNumber = 4;
    private global::Kronos.Core.Messages.DeleteResponse deleteResponse_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Kronos.Core.Messages.DeleteResponse DeleteResponse {
      get { return deleteResponse_; }
      set {
        deleteResponse_ = value;
      }
    }

    /// <summary>Field number for the "ContainsResponse" field.</summary>
    public const int ContainsResponseFieldNumber = 5;
    private global::Kronos.Core.Messages.ContainsResponse containsResponse_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Kronos.Core.Messages.ContainsResponse ContainsResponse {
      get { return containsResponse_; }
      set {
        containsResponse_ = value;
      }
    }

    /// <summary>Field number for the "CountResponse" field.</summary>
    public const int CountResponseFieldNumber = 6;
    private global::Kronos.Core.Messages.CountResponse countResponse_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Kronos.Core.Messages.CountResponse CountResponse {
      get { return countResponse_; }
      set {
        countResponse_ = value;
      }
    }

    /// <summary>Field number for the "ClearResponse" field.</summary>
    public const int ClearResponseFieldNumber = 7;
    private global::Kronos.Core.Messages.ClearResponse clearResponse_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Kronos.Core.Messages.ClearResponse ClearResponse {
      get { return clearResponse_; }
      set {
        clearResponse_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Response);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Response other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Type != other.Type) return false;
      if (!object.Equals(InsertResponse, other.InsertResponse)) return false;
      if (!object.Equals(GetRespone, other.GetRespone)) return false;
      if (!object.Equals(DeleteResponse, other.DeleteResponse)) return false;
      if (!object.Equals(ContainsResponse, other.ContainsResponse)) return false;
      if (!object.Equals(CountResponse, other.CountResponse)) return false;
      if (!object.Equals(ClearResponse, other.ClearResponse)) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Type != 0) hash ^= Type.GetHashCode();
      if (insertResponse_ != null) hash ^= InsertResponse.GetHashCode();
      if (getRespone_ != null) hash ^= GetRespone.GetHashCode();
      if (deleteResponse_ != null) hash ^= DeleteResponse.GetHashCode();
      if (containsResponse_ != null) hash ^= ContainsResponse.GetHashCode();
      if (countResponse_ != null) hash ^= CountResponse.GetHashCode();
      if (clearResponse_ != null) hash ^= ClearResponse.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Type != 0) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Type);
      }
      if (insertResponse_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(InsertResponse);
      }
      if (getRespone_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(GetRespone);
      }
      if (deleteResponse_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(DeleteResponse);
      }
      if (containsResponse_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(ContainsResponse);
      }
      if (countResponse_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(CountResponse);
      }
      if (clearResponse_ != null) {
        output.WriteRawTag(58);
        output.WriteMessage(ClearResponse);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Type != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
      }
      if (insertResponse_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(InsertResponse);
      }
      if (getRespone_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(GetRespone);
      }
      if (deleteResponse_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(DeleteResponse);
      }
      if (containsResponse_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ContainsResponse);
      }
      if (countResponse_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(CountResponse);
      }
      if (clearResponse_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ClearResponse);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Response other) {
      if (other == null) {
        return;
      }
      if (other.Type != 0) {
        Type = other.Type;
      }
      if (other.insertResponse_ != null) {
        if (insertResponse_ == null) {
          insertResponse_ = new global::Kronos.Core.Messages.InsertResponse();
        }
        InsertResponse.MergeFrom(other.InsertResponse);
      }
      if (other.getRespone_ != null) {
        if (getRespone_ == null) {
          getRespone_ = new global::Kronos.Core.Messages.GetResponse();
        }
        GetRespone.MergeFrom(other.GetRespone);
      }
      if (other.deleteResponse_ != null) {
        if (deleteResponse_ == null) {
          deleteResponse_ = new global::Kronos.Core.Messages.DeleteResponse();
        }
        DeleteResponse.MergeFrom(other.DeleteResponse);
      }
      if (other.containsResponse_ != null) {
        if (containsResponse_ == null) {
          containsResponse_ = new global::Kronos.Core.Messages.ContainsResponse();
        }
        ContainsResponse.MergeFrom(other.ContainsResponse);
      }
      if (other.countResponse_ != null) {
        if (countResponse_ == null) {
          countResponse_ = new global::Kronos.Core.Messages.CountResponse();
        }
        CountResponse.MergeFrom(other.CountResponse);
      }
      if (other.clearResponse_ != null) {
        if (clearResponse_ == null) {
          clearResponse_ = new global::Kronos.Core.Messages.ClearResponse();
        }
        ClearResponse.MergeFrom(other.ClearResponse);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            type_ = (global::Kronos.Core.Messages.RequestType) input.ReadEnum();
            break;
          }
          case 18: {
            if (insertResponse_ == null) {
              insertResponse_ = new global::Kronos.Core.Messages.InsertResponse();
            }
            input.ReadMessage(insertResponse_);
            break;
          }
          case 26: {
            if (getRespone_ == null) {
              getRespone_ = new global::Kronos.Core.Messages.GetResponse();
            }
            input.ReadMessage(getRespone_);
            break;
          }
          case 34: {
            if (deleteResponse_ == null) {
              deleteResponse_ = new global::Kronos.Core.Messages.DeleteResponse();
            }
            input.ReadMessage(deleteResponse_);
            break;
          }
          case 42: {
            if (containsResponse_ == null) {
              containsResponse_ = new global::Kronos.Core.Messages.ContainsResponse();
            }
            input.ReadMessage(containsResponse_);
            break;
          }
          case 50: {
            if (countResponse_ == null) {
              countResponse_ = new global::Kronos.Core.Messages.CountResponse();
            }
            input.ReadMessage(countResponse_);
            break;
          }
          case 58: {
            if (clearResponse_ == null) {
              clearResponse_ = new global::Kronos.Core.Messages.ClearResponse();
            }
            input.ReadMessage(clearResponse_);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
